Repository Hennepin-County/MAXIS-scripts, pull requests merged in 2021-07, with the labels that each got.

#513 #107 Update function start_a_new_spec_memo - now it has ALL the parameters
  MASTER FUNCTIONS LIBRARY.vbs
  actions/job-change-reported.vbs
  actions/transfer-case.vbs
  admin/cs-good-cause.vbs
  admin/individual-appointment-letter.vbs
  admin/individual-nomi.vbs
  admin/individual-recertification-notices.vbs
  admin/memo-from-list.vbs
  admin/unea-updater.vbs
  bulk/case-transfer.vbs
  dail/fmed-deduction.vbs
  dail/overdue-baby.vbs
  notes/application-received.vbs
  notes/closed-programs.vbs
  notes/health-care-transition.vbs
  notes/interview-no-show.vbs
  notes/significant-change.vbs
  notices/12-month-contact.vbs
  notices/dwp-es-referral.vbs
  notices/eligibility-notifier.vbs
  notices/ltc-asset-transfer.vbs
  notices/method-b-wcom.vbs
  notices/pa-verif-request.vbs
  notices/snap-e-and-t-letter.vbs
  shelter/shelter-mandatory-vendor-approved.vbs
  shelter/shelter-mandatory-vendor-memo.vbs
Labels: Category: FuncLib, Type: Enhancement

#505 #62 NOTES - Interview - ready to get ready for testing
  actions/full-interview.vbs
  notes/interview.vbs
Labels: Category: NOTES, Jar: Boulder, Type: New Script

#517 HSS Housing Supports - TEST Pull
  locally-installed-files/Housing Support Power Pad.pad
  locally-installed-files/authorization-update-redirect.vbs
  locally-installed-files/data-report-redirect.vbs
  misc/authorization-update-redirect.vbs
  misc/data-report-redirect.vbs
  misc/hss-maxis-facility-report.vbs
  misc/hss-service-authorization-update.vbs
Labels: Type: New Script

#522 #999 - Only for documentation purposes
  Test scripts/Casey/Utilities/handy-make-a-note.vbs
Labels: Category: ADMIN, Type: Housekeeping

#524 DHS HSS Housing Supports Scripts: Pull request for final testing series
  locally-installed-files/HSS Power Pad.pad
  locally-installed-files/Housing Support Power Pad.pad
  misc/hss-maxis-facility-report.vbs
  misc/hss-service-authorization-update.vbs
  misc/redirects/add-rate-2-to-mmis-redirect.vbs
  misc/redirects/authorization-update-redirect.vbs
  misc/redirects/calculate-rate-2-units-redirect.vbs
  misc/redirects/case-note-from-list-redirect.vbs
  misc/redirects/data-report-redirect.vbs
  misc/redirects/health-care-report-redirect.vbs
  misc/redirects/nav-mmis-grh-redirect.vbs
Labels: Category: BULK, Category: Updater, Jar: Boulder, Type: New Script

#528 #473 - Added supports for if the agreement date is after the HSS date
  misc/hss-service-authorization-update.vbs
Labels: Category: ACTIONS, Jar: Boulder, Type: New Script

#533 #515 NOTES CAF - Reading the details of previous notes for autofil in the CAF script run
  notes/caf.vbs
Labels: Category: NOTES, Jar: Pebbles, Type: Enhancement

#538 #537 FUNC LIB - adding definition of FSO and MyDocs folder - Deleting old 'save your work' files
  MASTER FUNCTIONS LIBRARY.vbs
  Test scripts/Casey/functions/erase_txt_files.vbs
  admin/work-assignment-from-excel.vbs
  notes/interview.vbs
  utilities/complete-phone-caf.vbs
  utilities/complete-phone-csr.vbs
Labels: Category: FuncLib, Jar: Pebbles, Type: Housekeeping

#535 #506 NOTICES - PA Verif add GRH Functionality
  notices/pa-verif-request.vbs
Labels: Category: NOTICES, Jar: Sand
