Repository Hennepin-County/MAXIS-scripts, pull requests merged in 2022-06, with the labels that each got.

#869 #393 ACTIONS - TRANSFER CASE - bug fix
  actions/transfer-case.vbs
Labels: CRITICAL

#872 #498 BULK - DEU-MATCH CLEARED - bug reported
  deu/bulk-match-cleared.vbs
Labels: Type: Bug

#879 873 dail remedial care updates
  dail/ltc-remedial-care.vbs
Labels: Category: Updater, Type: Housekeeping, Category: DAIL, Jar: Water

#881 880 paris dail bug
  deu/paris-match-cleared.vbs
Labels: Type: Bug, Type: Enhancement, CRITICAL, Category: DAIL, Jar: Water

#885 #866 FuncLib: Updated navigation strings to UpperCase
  MASTER FUNCTIONS LIBRARY.vbs
Labels: Category: FuncLib, Type: Housekeeping, Jar: Water
